schema {
  query: Query
}

type Query {
  users: [User!]!
}

type User {
  id: ID!
  name: String
  email: String!
  password: String!
}

query ALL_USERS {
  usersCollection {
    edges {
      node {
        id
        name
      }
    }
  }
}

mutation SignUpMutation(
  $email: String!
  $password: String!
  $username: String!
) {
  sign_up_user(p_email: $email, p_password: $password, p_username: $username) {
    id
    name
    email
    password
  }
}

mutation SignIn($email: String!, $password: String!) {
  sign_in_user(p_email: $email, p_password: $password) {
    email
    password
    id
  }
}

type Mutation {
  signUp(name: String!, email: String!, password: String!): User
  signIn(email: String!, password: String!): User
}
