schema {
  query: Query
}

type Query {
  users: [User!]!
}

type User {
  id: ID!
  name: String
  email: String!
  password: String!
}

query ALL_USERS {
  users {
    name
  }
}

mutation SignUpMutation(
  $email: String!
  $password: String!
  $username: String!
) {
  signUp(email: $email, password: $password, name: $username) {
    id
    name
    email
    password
  }
}

mutation SignIn($email: String!, $password: String!) {
  signIn(email: $email, password: $password) {
    email
    password
    id
  }
}

type Mutation {
  signUp(name: String!, email: String!, password: String!): User
  signIn(email: String!, password: String!): User
}
